repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
      - id: clang-format
        files: ^(api|core|wrapper)/.*\.(h|cc|cpp|c)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        files: ^(py/|tests/|benchmarks/|setup\.py)
